### ISSUE TITLE
How can I fix: File mode specification error: (void-variable ac-modes) 

### ISSUE THREAD

**Issue by avatar-lavventura** [Wilfred/pip-requirements.el#19]
When I launch `pip-requirements.el` I keep getting following warning error message:

`File mode specification error: (void-variable ac-modes)`

How can I fix this error?

**Comment by Wilfred** [comment]
I can't reproduce. What version of Emacs? Could you describe what you're doing?

**Comment by avatar-lavventura** [comment]
I am using : ```GNU Emacs 28.0.92```.

I have managed this error but I have to remove pip-requirements package. It consumes a heavy memory when a `requirements.tex` file is opened, which freezes machines with 1 or 2 GiB RAM.
